services:
  app-one:
    build:
      context: ./app-one/.
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - node-app-network

  app-two:
    build:
      context: ./app-two/.
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    networks:
      - node-app-network

networks:
  node-app-network:
    driver: bridge


